# coding: utf-8
 
             
Lodge.create!(lodge:  "HOTEL NUPKA",
             prefecture: "北海道",
             postal_code: "〒080-0012",
             address: "帯広市西2条南10-20-3",
             phone_number: "TEL 0155-20-2600",
             map: "https://goo.gl/maps/5cR6gQSUoTDskTNY7",
             type: "hostel",
             hp_link: "https://www.nupka.jp/",
             roomtype: "Roomtype: Male dormitory, Female dormitory, Single, Double",
             instagram: "https://www.instagram.com/hotel_nupka/?hl=ja",
             facebook: "https://www.facebook.com/hotel.cafe.nupka",
             image:File.open("./app/assets/images/NUPKA.main.jpg"),
             image2:File.open("./app/assets/images/NUPKA.room.png"),
             image3:File.open("./app/assets/images/NUPKA.dorm.png")
             )



Lodge.create!(lodge:  "屈斜路原野ユースゲストハウス",
             prefecture: "北海道",
             postal_code: "〒088-3341",
             address: "川上郡弟子屈町字屈斜路原野443-1",
             phone_number: "TEL 015-484-2609",
             map: "https://goo.gl/maps/tXr796jbZ6QKu3cz6",
             type: "hostel",
             hp_link: "https://www.gogogenya.com/",
             roomtype: "Roomtype: Male dormitory, Female dormitory, Quadruple",
             instagram: "",
             facebook: "https://www.facebook.com/gogogenya/",
             image:File.open("./app/assets/images/屈斜路.main.jpg"),
             image2:File.open("./app/assets/images/屈斜路.active.jpg"),
             image3:File.open("./app/assets/images/屈斜路.room.jpg")
             )
             
Lodge.create!(lodge:  "ユースゲストハウスATOMA",
             prefecture: "福島県",
             postal_code: "〒960-2151",
             address: "福島市桜本舟石15-2",
             phone_number: "TEL 024-591-2523",
             map: "https://g.page/go-atoma?share",
             type: "hostel",
             hp_link: "http://www006.upp.so-net.ne.jp/atoma/",
             roomtype: "Roomtype: Triple, Double, Modern room, Group room",
             instagram: "https://www.instagram.com/hiranosyunichi/?hl=ja",
             facebook: "https://www.facebook.com/%E3%83%A6%E3%83%BC%E3%82%B9%E3%82%B2%E3%82%B9%E3%83%88%E3%83%8F%E3%82%A6%E3%82%B9%E3%82%A2%E3%83%88%E3%83%9E-462622630460609/",
             image:File.open("./app/assets/images/ATOMA.main.jpg"),
             image2:File.open("./app/assets/images/ATOMA.lobby.jpg"),
             image3:File.open("./app/assets/images/ATOMA.room.jpg")
             )
    
Lodge.create!(lodge:  "糖平温泉 中村屋",
             prefecture: "北海道",
             postal_code: "〒080-1403",
             address: "河東郡上士幌町字ぬかびら源泉郷南区",
             phone_number: "TEL 01564-4-2311",
             map: "https://goo.gl/maps/nXguWLRo8YLt2Mqk7",
             type: "hotel",
             hp_link: "https://nukabira-nakamuraya.com/index.html",
             roomtype: "Roomtype: Twin room, Double room",
             instagram: "https://www.instagram.com/nukabira_onsen/?hl=ja",
             facebook: "https://www.facebook.com/%E7%B3%A0%E5%B9%B3%E6%B8%A9%E6%B3%89-%E4%B8%AD%E6%9D%91%E5%B1%8B-341924642578314",
             image:File.open("./app/assets/images/中村屋.main.jpg"),
             image2:File.open("./app/assets/images/中村屋.bath.jpg"),
             image3:File.open("./app/assets/images/中村屋.room.jpg")
             )
             
Lodge.create!(lodge:  "LANDABOUT",
             prefecture: "東京都",
             postal_code: "〒110-0003",
             address: "台東区根岸3-4−5",
             phone_number: "TEL 03-6802-4431",
             map: "https://g.page/landabout?share",
             type: "hotel",
             hp_link: "https://landabout.com/",
             roomtype: "Roomtype: Universal, Superior queen, Family, Connecting, Deluxe Twin, Twin, Double",
             instagram: "https://www.instagram.com/landabout_tokyo/?hl=ja",
             facebook: "https://www.facebook.com/landabout.tokyo",
             image:File.open("./app/assets/images/LANDABOUT.main.jpg"),
             image2:File.open("./app/assets/images/LANDABOUT.lobby.jpg"),
             image3:File.open("./app/assets/images/LANDABOUT.room.jpg")
             )
             
Lodge.create!(lodge:  "Hotel Noum OSAKA",
             prefecture: "大阪府",
             postal_code: "〒530-0043",
             address: "大阪市北区天満4-1−18",
             phone_number: "TEL 06-6940-0882",
             map: "https://g.page/hotelnoum?share",
             type: "hotel",
             hp_link: "https://www.no-um.jp/",
             roomtype: "Roomtype: King with river view, Double with river view, Double, Twin, Superior Single, Single",
             instagram: "https://www.instagram.com/noum_osaka/?hl=ja",
             facebook: "https://www.facebook.com/hotelnoum",
             image:File.open("./app/assets/images/Noum.main.png"),
             image2:File.open("./app/assets/images/Noum.breakfast.png"),
             image3:File.open("./app/assets/images/Noum.room.png")
             )
             
Lodge.create!(lodge:  "HOTEL SHE, OSAKA",
             prefecture: "大阪府",
             postal_code: "〒552-0012",
             address: "大阪市港区市岡1丁目2−5",
             phone_number: "TEL 06-6577-5500",
             map: "https://goo.gl/maps/4bH1kd7ybk8kpkdr5",
             type: "hotel",
             hp_link: "https://www.hotelsheosaka.com/",
             roomtype: "Roomtype: Deluxe Double, Superior Double, Superior Twin",
             instagram: "https://www.instagram.com/hotelsheosaka/?hl=ja",
             facebook: "https://www.facebook.com/hotelsheosaka",
             image:File.open("./app/assets/images/SHE_OSAKA.main.jpg"),
             image2:File.open("./app/assets/images/SHE_OSAKA.lobby.jpg"),
             image3:File.open("./app/assets/images/SHE_OSAKA.room.jpg")
             )
            
Lodge.create!(lodge:  "HOTEL SHE, KYOTO",
             prefecture: "京都府",
             postal_code: "〒601-8041",
             address: "京都市南区東九条南烏丸町16",
             phone_number: "TEL 075-634-8340",
             map: "https://goo.gl/maps/YZPUQzgbBNpALDoa8",
             type: "hotel",
             hp_link: "https://www.hotelshekyoto.com/",
             roomtype: "Roomtype: Superior Double with kitchen, Superior Double, Double, Twin",
             instagram: "https://www.instagram.com/hotelshekyoto/?hl=ja",
             facebook: "https://www.facebook.com/hotelshekyoto",
             image:File.open("./app/assets/images/SHE_KYOTO.main.jpg"),
             image2:File.open("./app/assets/images/SHE_KYOTO.ice.jpg"),
             image3:File.open("./app/assets/images/SHE_KYOTO.room.jpg")
             )
             
Lodge.create!(lodge:  "THIRD ISHIGAKI",
             prefecture: "沖縄県",
             postal_code: "〒907-0012",
             address: "石垣市美崎町4−7",
             phone_number: "TEL ",
             map: "https://goo.gl/maps/dmPdq768JnC7Z6Wh8",
             type: "hotel",
             hp_link: "https://hotelthird.com/",
             roomtype: "Roomtype: Suite, Superior Loft Sea View, Junior Suite Sea View, Deluxe Loft Sea View, Twin",
             instagram: "https://www.instagram.com/hotel_third.ishigaki/?hl=ja",
             facebook: "https://www.facebook.com/THIRD%E7%9F%B3%E5%9E%A3%E5%B3%B6third-Ishigaki-111817583776745",
             image:File.open("./app/assets/images/THIRD.terrace.jpg"),
             image2:File.open("./app/assets/images/THIRD.lobby.png"),
             image3:File.open("./app/assets/images/THIRD.room.png")
             )
             
Lodge.create!(lodge:  "瀬戸内リトリート青凪",
             prefecture: "愛媛県",
             postal_code: "〒799-2641",
             address: "松山市柳谷町794−1",
             phone_number: "TEL 089-977-9500",
             map: "https://g.page/setouchiaonagi?share",
             type: "hotel",
             hp_link: "https://www.setouchi-aonagi.com/",
             roomtype: "Roomtype: THE AONAGI Suite, Suite with Open-air-bath, Garden Suite, Suite with 4 beds",
             instagram: "https://www.instagram.com/setouchi_aonagi/?hl=ja",
             facebook: "https://www.facebook.com/setouchiaonagi",
             image:File.open("./app/assets/images/青凪.main.jpg"),
             image2:File.open("./app/assets/images/青凪.lobby.png"),
             image3:File.open("./app/assets/images/青凪.room.png")
             )
             
Lodge.create!(lodge:  "THE BOLY OSAKA",
             prefecture: "大阪府",
             postal_code: "〒541-0041",
             address: "大阪市中央区北浜2-1-16",
             phone_number: "TEL 06-6222-7768",
             map: "https://goo.gl/maps/6WgBByoWXn3Evbu58",
             type: "hotel",
             hp_link: "https://theboly.com/",
             roomtype: "Roomtype: Suite with river view, Suite with city view, Deluxe Twin, Queen with balcony, Queen",
             instagram: "https://www.instagram.com/thebolyosaka/?hl=ja",
             facebook: "https://www.facebook.com/thebolyosaka",
             image:File.open("./app/assets/images/BOLY.main.jpg"),
             image2:File.open("./app/assets/images/BOLY.lobby.jpg"),
             image3:File.open("./app/assets/images/BOLY.room.jpg")
             )
             
Lodge.create!(lodge:  "HOTEL TRIM (女性専用)",
             prefecture: "石川県",
             postal_code: "〒920-0852",
             address: "金沢市此花町9-18",
             phone_number: "TEL 090-1392-8309",
             map: "https://g.page/hoteltrim-kanazawa?share",
             type: "hotel",
             hp_link: "https://hotel-trim.com/",
             roomtype: "Roomtype: Queen room, Twin room",
             instagram: "https://www.instagram.com/trimkanazawa/?hl=ja",
             facebook: "https://www.facebook.com/trimkanazawa/",
             image:File.open("./app/assets/images/TRIM.main.jpg"),
             image2:File.open("./app/assets/images/TRIM.lobby.jpg"),
             image3:File.open("./app/assets/images/TRIM.room.jpg")
             )
             
Lodge.create!(lodge:  "ホテルインディゴ箱根強羅",
             prefecture: "神奈川県",
             postal_code: "〒250-0402",
             address: "足柄下郡箱根町木賀924-1",
             phone_number: "TEL 0460-83-8310",
             map: "https://g.page/hotelindigohakone?share",
             type: "hotel",
             hp_link: "https://hakonegora.hotelindigo.com/",
             roomtype: "Roomtype: Premium Suite, Deluxe King with river side or hill side, Deluxe Twin with river side or hill side, Deluxe",
             instagram: "https://www.instagram.com/hotelindigohakonegora/?hl=ja",
             facebook: "https://www.facebook.com/hotelindigohakone",
             image:File.open("./app/assets/images/インディゴ.main.jpg"),
             image2:File.open("./app/assets/images/インディゴ.lobby.jpg"),
             image3:File.open("./app/assets/images/インディゴ.room.jpg")
             )             
             
Lodge.create!(lodge:  "AMANEMU",
             prefecture: "三重県",
             postal_code: "〒517-0403 ",
             address: "志摩市浜島町迫子2165",
             phone_number: "TEL 0599-52-5000",
             map: "https://g.page/amanemu?share",
             type: "hotel",
             hp_link: "https://www.aman.com/ja-jp/resorts/amanemu/destination",
             roomtype: "Roomtype: Suite with sea view, Suite with forest view",
             instagram: "https://www.instagram.com/amanemu_resort/?hl=ja",
             facebook: "https://www.facebook.com/amanemuresort",
             image:File.open("./app/assets/images/アマネム.main.jpg"),
             image2:File.open("./app/assets/images/アマネム.lobby.jpg"),
             image3:File.open("./app/assets/images/アマネム.room.jpg")
             )
             
Lodge.create!(lodge:  "hotel aiaoi",
             prefecture: "神奈川県",
             postal_code: "〒248-0016",
             address: "鎌倉市長谷2-16-15 サイトウビル3F",
             phone_number: "TEL 0467-22-6789",
             map: "https://goo.gl/maps/YaaVE7MQsakyTj729",
             type: "hotel",
             hp_link: "http://aiaoi.net/",
             roomtype: "Roomtype: Double with Loft, Double, Twin, Single",
             instagram: "https://www.instagram.com/hotel_aiaoi/?hl=ja",
             facebook: "https://www.facebook.com/hotelaiaoi",
             image:File.open("./app/assets/images/aiaoi.main.png"),
             image2:File.open("./app/assets/images/aiaoi.lobby.png"),
             image3:File.open("./app/assets/images/aiaoi.room.png")
             )
             
Lodge.create!(lodge:  "Why Kumano Hostel&Cafe bar",
             prefecture: "和歌山県",
             postal_code: "〒649-5335",
             address: "東牟婁郡那智勝浦町大字築地5-1-3 2F",
             phone_number: "TEL 0735-30-0921",
             map: "https://goo.gl/maps/RyZzUdHRrocrEtAi7",
             type: "hostel",
             hp_link: "https://www.kumano-travel.com/ja/accommodations/why-kumano-hostel-and-cafe-bar",
             roomtype: "Roomtype: Mix Dormitory, Female Dormitory, Private Room for 4 people",
             instagram: "https://www.instagram.com/whykumano/?hl=ja",
             facebook: "https://www.facebook.com/whykumano",
             image:File.open("./app/assets/images/kumano.main.jpg"),
             image2:File.open("./app/assets/images/kumano.lobby.jpg"),
             image3:File.open("./app/assets/images/kumano.room.jpg")
             )
             
Lodge.create!(lodge:  "Tokyo Guesthouse Oji music lounge",
             prefecture: "東京都",
             postal_code: "〒114-0023",
             address: "北区滝野川2-4-17",
             phone_number: "TEL 03-6903-7256",
             map: "https://g.page/Ojimusiclounge?share",
             type: "hostel",
             hp_link: "http://oji-music-lounge.tokyo/hp-jp/",
             roomtype: "Roomtype: Mix Dormitory, Female Dormitory, Family, Superior Twin, Twin, Double",
             instagram: "https://www.instagram.com/tghoml/?hl=ja",
             facebook: "https://www.facebook.com/tokyoguesthouseouji",
             image:File.open("./app/assets/images/oji.main.jpg"),
             image2:File.open("./app/assets/images/oji.lobby.jpg"),
             image3:File.open("./app/assets/images/oji.room.jpg")
             )
            
Lodge.create!(lodge:  "OKINAWA HARBORVIEW HOTEL",
             prefecture: "沖縄県",
             postal_code: "〒900-0021",
             address: "那覇市泉崎2-46",
             phone_number: "TEL 098-853-2111",
             map: "https://goo.gl/maps/kjinVTXVy6oVhY7L6",
             type: "hotel",
             hp_link: "https://oka-hvh.com/index.html",
             roomtype: "Roomtype: Superior Twin, Twin, Club member Hollywood Twin or Twin or Double",
             instagram: "https://www.instagram.com/okinawa_harborview_hotel/?hl=ja",
             facebook: "https://www.facebook.com/okinawa.harborview",
             image:File.open("./app/assets/images/ハーバー.main.jpg"),
             image2:File.open("./app/assets/images/ハーバー.lobby.jpg"),
             image3:File.open("./app/assets/images/ハーバー.room.jpg")
             )

Lodge.create!(lodge:  "眺望の宿しおり",
             prefecture: "大分県",
             postal_code: "〒874-0839",
             address: "別府市大字南立石2218-5",
             phone_number: "TEL 0977-22-9771",
             map: "https://goo.gl/maps/a1cBVKaUJEafotgL6",
             type: "hotel",
             hp_link: "http://www.yado-shiori.jp/index.html",
             roomtype: "Roomtype: Japanese modern room",
             instagram: "https://www.instagram.com/beppushiori/?hl=ja",
             facebook: "https://www.facebook.com/beppushiori",
             image:File.open("./app/assets/images/しおり.main.jpg"),
             image2:File.open("./app/assets/images/しおり.lobby.jpg"),
             image3:File.open("./app/assets/images/しおり.room.jpg")
             )
             
Lodge.create!(lodge:  "ANAインターコンチネンタル万座ビーチリゾート",
             prefecture: "沖縄県",
             postal_code: "〒904-0493",
             address: "恩納村字瀬良垣2260",
             phone_number: "TEL 098-966-1211",
             map: "https://g.page/ANAICManza?share",
             type: "hotel",
             hp_link: "https://www.anaintercontinental-manza.jp/",
             roomtype: "Roomtype: Superior Twin with Beach view or Ocean view, Deluxe Twin, Twin",
             instagram: "https://www.instagram.com/ana.ic.manza.beach.resort/?hl=ja",
             facebook: "https://www.facebook.com/ANAInterContinentalManzaBeachResort",
             image:File.open("./app/assets/images/万座.main.jpg"),
             image2:File.open("./app/assets/images/万座.lobby.jpg"),
             image3:File.open("./app/assets/images/万座.room.jpg")
             )
             
Lodge.create!(lodge:  "妙義温泉・グリーンホテル＆テラス",
             prefecture: "群馬県",
             postal_code: "〒379-0208",
             address: "富岡市妙義町菅原2678",
             phone_number: "TEL 0274-73-4111",
             map: "https://goo.gl/maps/FbLeE1i5oQDzLiiK8",
             type: "hotel",
             hp_link: "https://www.accordiahotel.com/myogi/",
             roomtype: "Roomtype: Japanese modern room, Superior, Double, Twin",
             instagram: "https://www.instagram.com/glamping_myogi/?hl=ja",
             facebook: "",
             image:File.open("./app/assets/images/妙義.main.jpg"),
             image2:File.open("./app/assets/images/妙義.lobby.jpg"),
             image3:File.open("./app/assets/images/妙義.room.jpg")
             )
             
Lodge.create!(lodge:  "八幡野温泉郷 杜の湯 きらの里",
             prefecture: "静岡県",
             postal_code: "〒413-0232",
             address: "伊東市八幡野1326-5",
             phone_number: "TEL 0557-55-3311",
             map: "https://goo.gl/maps/QmxWxeMP9CvHxzYi8",
             type: "hotel",
             hp_link: "https://www.hotespa.net/hotels/kiranosato/",
             roomtype: "Roomtype: Japanese western room, Japanese modern room, Double",
             instagram: "https://www.instagram.com/kiranosato/?hl=ja",
             facebook: "https://www.facebook.com/kiranosato",
             image:File.open("./app/assets/images/きらの里.main.jpg"),
             image2:File.open("./app/assets/images/きらの里.lobby.jpg"),
             image3:File.open("./app/assets/images/きらの里.room.jpg")
             )

Lodge.create!(lodge:  "ショウナイホテル スイデンテラス",
             prefecture: "山形県",
             postal_code: "〒997-0053",
             address: "鶴岡市北京田下鳥ノ巣23-1",
             phone_number: "TEL 0235-25-7424",
             map: "https://goo.gl/maps/MrhT18WnKS91yVv56",
             type: "hotel",
             hp_link: "https://suiden-terrasse.yamagata-design.com/",
             roomtype: "Roomtype: Family, Triple, Superior Twin, Twin, Large Double, Double",
             instagram: "",
             facebook: "https://www.facebook.com/suiden.terrasse",
             image:File.open("./app/assets/images/水田.main.jpg"),
             image2:File.open("./app/assets/images/水田.lobby.jpg"),
             image3:File.open("./app/assets/images/水田.room.jpg")
             )
             
Lodge.create!(lodge:  "里海邸 金波楼本邸",
             prefecture: "茨城県",
             postal_code: "〒311-1301",
             address: "東茨城郡大洗町磯浜町6883",
             phone_number: "TEL 029-267-2101",
             map: "https://goo.gl/maps/wyBC9PjSx6RBBTGPA",
             type: "hotel",
             hp_link: "https://www.satoumitei.jp/",
             roomtype: "Roomtype: Terrace Suite, Japanese Modern Room, Twin",
             instagram: "https://www.instagram.com/satoumitei/?hl=ja",
             facebook: "https://www.facebook.com/satoumitei",
             image:File.open("./app/assets/images/里海.main.png"),
             image2:File.open("./app/assets/images/里海.lobby.png"),
             image3:File.open("./app/assets/images/里海.room.png")
             )
             
Lodge.create!(lodge:  "Chus",
             prefecture: "栃木県",
             postal_code: "〒325-0045",
             address: "那須塩原市高砂町6-3",
             phone_number: "TEL 0287-74-5156",
             map: "https://goo.gl/maps/k65k2Xjh6rTYby3N7",
             type: "hostel",
             hp_link: "https://chus-nasu.com/",
             roomtype: "Roomtype: Mix Dormitory, Futon, Loft, Double, Twin",
             instagram: "https://www.instagram.com/chus_table/?hl=ja",
             facebook: "https://www.facebook.com/chus.nasu",
             image:File.open("./app/assets/images/Chus.main.jpg"),
             image2:File.open("./app/assets/images/Chus.lobby.jpg"),
             image3:File.open("./app/assets/images/Chus.room.png")
             )

Lodge.create!(lodge:  "THE CHIKURA UMI BASE CAMP",
             prefecture: "千葉県",
             postal_code: "〒295-0003",
             address: "南房総市千倉町白子2521-4",
             phone_number: "TEL 0470-29-5975",
             map: "https://goo.gl/maps/Jr8so1oLVM57LfJ19",
             type: "ryokan",
             hp_link: "https://chikuraumi.basecamp.style/",
             roomtype: "Roomtype: House for 4 people, House for 8 people",
             instagram: "https://www.instagram.com/thechikuraumibasecamp/?hl=ja",
             facebook: "https://www.facebook.com/The-Chikuraumi-basecamp-286238858581560",
             image:File.open("./app/assets/images/chikura.main.png"),
             image2:File.open("./app/assets/images/chikura.lobby.png"),
             image3:File.open("./app/assets/images/chikura.room.png")
             )
             
Lodge.create!(lodge:  "HAKONE TENT",
             prefecture: "神奈川県",
             postal_code: "〒250-0408",
             address: "足柄下郡箱根町強羅1320-257",
             phone_number: "TEL 0460-83-8021",
             map: "https://goo.gl/maps/Vn2ap2mWqaSwAQqKA",
             type: "hostel",
             hp_link: "http://hakonetent.com/jp/",
             roomtype: "Roomtype: Male dormitory(Futon), Female dormitory(Futon), Apartment for 6 people, Japanese Modern room for 2~4 people, Double",
             instagram: "https://www.instagram.com/hakonetent/?hl=ja",
             facebook: "https://www.facebook.com/hakonetent",
             image:File.open("./app/assets/images/HAKONE_TENT.main.jpg"),
             image2:File.open("./app/assets/images/HAKONE_TENT.lobby.jpg"),
             image3:File.open("./app/assets/images/HAKONE_TENT.room.jpg")
             )
             
Lodge.create!(lodge:  "tu.ne.Hostel",
             prefecture: "千葉県",
             postal_code: "〒294-0045",
             address: "館山市北条1712",
             phone_number: "TEL 0470-29-7974",
             map: "https://g.page/tunehostel?share",
             type: "hostel",
             hp_link: "https://tune.co.jp/",
             roomtype: "Roomtype: Male dormitory, Female dormitory, Superior Twin, Twin",
             instagram: "https://www.instagram.com/tu.ne.hostel/?hl=ja",
             facebook: "https://www.facebook.com/tu.ne.hostel",
             image:File.open("./app/assets/images/tune.main.jpg"),
             image2:File.open("./app/assets/images/tune.lobby.jpg"),
             image3:File.open("./app/assets/images/tune.room.jpg")
             )
             
Lodge.create!(lodge:  "箱根リトリートföre",
             prefecture: "神奈川県",
             postal_code: "〒250-0631",
             address: "足柄下郡箱根町仙石原1286-116",
             phone_number: "TEL 0470-29-7974",
             map: "https://goo.gl/maps/dxUG71ALr39P39eZ6",
             type: "hotel",
             hp_link: "https://www.hakone-retreat.com/hotel/",
             roomtype: "Roomtype: Suite with Terrace, Deluxe Double, Superior Double, Superior Twin",
             instagram: "https://www.instagram.com/hakone.retreat/?hl=ja",
             facebook: "https://www.facebook.com/hakone.retreat",
             image:File.open("./app/assets/images/fore.main.jpg"),
             image2:File.open("./app/assets/images/fore.lobby.jpg"),
             image3:File.open("./app/assets/images/fore.room.jpg")
             )
             
Lodge.create!(lodge:  "なり -nuttari NARI-",
             prefecture: "新潟県",
             postal_code: "〒950-0075",
             address: "新潟市中央区沼垂東2-11-31",
             phone_number: "TEL 025-369-4126",
             map: "https://goo.gl/maps/4nBiE193gX626vZg8",
             type: "hostel",
             hp_link: "https://nuttari-nari.com/",
             roomtype: "Roomtype: Male dormitory, Female dormitory, Double, Traditional Japanese room",
             instagram: "https://www.instagram.com/nuttari_nari/?hl=ja",
             facebook: "https://www.facebook.com/nari.nuttarinari",
             image:File.open("./app/assets/images/nari.main.png"),
             image2:File.open("./app/assets/images/nari.lobby.png"),
             image3:File.open("./app/assets/images/nari.room.png")
             )
             
Lodge.create!(lodge:  "川崎キングスカイフロント東急REIホテル",
             prefecture: "神奈川県",
             postal_code: "〒210-0821",
             address: "川崎市川崎区殿町3-25-11",
             phone_number: "TEL 044-280-1090",
             map: "https://goo.gl/maps/TdeCtBzpRBUtKgDb9",
             type: "hotel",
             hp_link: "https://www.tokyuhotels.co.jp/kawasaki-r/",
             roomtype: "Roomtype: Superior Queen, Superior Double, Premium Double, Superior Large Twin, Superior Twin, Twin",
             instagram: "https://www.instagram.com/kingskyfront_tokyu_rei/?hl=ja",
             facebook: "https://www.facebook.com/KawasakiKingSkyfrontTokyuREIHotel",
             image:File.open("./app/assets/images/REI.main.jpg"),
             image2:File.open("./app/assets/images/REI.lobby.jpg"),
             image3:File.open("./app/assets/images/REI.room.jpg")
             )
Lodge.create!(lodge:  "里山のオーベルジュ 薪の音",
             prefecture: "富山県",
             postal_code: "〒939-1844",
             address: "南砺市野口140",
             phone_number: "TEL 0763-62-3255",
             map: "https://goo.gl/maps/geNQ1pRvWttnCQu27",
             type: "hotel",
             hp_link: "https://makinooto.co.jp/",
             roomtype: "Roomtype: Junior Suite, Deluxe Japanese Modern, Deluxe Twin",
             instagram: "https://www.instagram.com/makinootokanazawa/?hl=ja",
             facebook: "https://www.facebook.com/%E9%87%8C%E5%B1%B1%E3%81%AE%E3%82%AA%E3%83%BC%E3%83%99%E3%83%AB%E3%82%B8%E3%83%A5-%E8%96%AA%E3%81%AE%E9%9F%B3-152658131538212",
             image:File.open("./app/assets/images/薪の音.main.jpg"),
             image2:File.open("./app/assets/images/薪の音.lobby.jpg"),
             image3:File.open("./app/assets/images/薪の音.room.png")
             )
Lodge.create!(lodge:  "off Hostel in Kanazawa",
             prefecture: "石川県",
             postal_code: "〒920-0852",
             address: "金沢市此花町4-19",
             phone_number: "TEL 090-1392-8309",
             map: "https://g.page/offkanazawa?share",
             type: "hostel",
             hp_link: "https://offkanazawa.com/",
             roomtype: "Roomtype: Deluxe Family, Family, Twin",
             instagram: "",
             facebook: "https://www.facebook.com/offkanazawa",
             image:File.open("./app/assets/images/off.main.jpg"),
             image2:File.open("./app/assets/images/off.lobby.jpg"),
             image3:File.open("./app/assets/images/off.room.jpg")
             )
             
Lodge.create!(lodge:  "ゲストハウス白",
             prefecture: "石川県",
             postal_code: "〒920-0852",
             address: "金沢市此花町4-19",
             phone_number: "TEL 090-1392-8309",
             map: "https://g.page/guesthouse-shiro?share",
             type: "hostel",
             hp_link: "https://guesthouse-shiro.com/",
             roomtype: "Roomtype: Japanese Modern, Double",
             instagram: "https://www.instagram.com/guesthouse_shiro/?hl=ja",
             facebook: "https://www.facebook.com/guesthouse.shiro",
             image:File.open("./app/assets/images/白.main.png"),
             image2:File.open("./app/assets/images/白.lobby.png"),
             image3:File.open("./app/assets/images/白.room.png")
             )
        
Lodge.create!(lodge:  "ZEN&BED 望月庵",
             prefecture: "山梨県",
             postal_code: "〒404-0053",
             address: "甲州市塩山小屋敷2295",
             phone_number: "TEL 090-8857-6696",
             map: "https://goo.gl/maps/cjqVkTmvYxz1YjFG6",
             type: "hotel",
             hp_link: "https://zenandbed.com/",
             roomtype: "Roomtype: Double room, Twin room",
             instagram: "",
             facebook: "https://www.facebook.com/Zenbed-%E6%9C%9B%E6%9C%88%E5%BA%B5-1342092552565987",
             image:File.open("./app/assets/images/ZEN.main.jpg"),
             image2:File.open("./app/assets/images/ZEN.lobby.jpg"),
             image3:File.open("./app/assets/images/ZEN.room.jpg")
             )
             
Lodge.create!(lodge:  "Retreat camp まほろば",
             prefecture: "山梨県",
             postal_code: "〒401-0304",
             address: "南都留郡富士河口湖町河口 山宮2552",
             phone_number: "TEL 090-4128-6066",
             map: "https://g.page/Retreat-camp-mahoroba?share",
             type: "hotel",
             hp_link: "https://retreatcamp-mahoroba.net/charge/",
             roomtype: "Roomtype: Double room, Twin room",
             instagram: "https://www.instagram.com/retreatcamp_mahoroba/?hl=ja",
             facebook: "https://www.facebook.com/Retreat-camp-%E3%81%BE%E3%81%BB%E3%82%8D%E3%81%B0-1900003753366631",
             image:File.open("./app/assets/images/まほろば.main.png"),
             image2:File.open("./app/assets/images/まほろば.lobby.png"),
             image3:File.open("./app/assets/images/まほろば.room.png")
             )
             
Lodge.create!(lodge:  "泊まれる公園 INN THE PARK",
             prefecture: "静岡県",
             postal_code: "〒410-0001",
             address: "沼津市足高220-4",
             phone_number: "TEL 055-939-8366",
             map: "https://goo.gl/maps/Sf5JnbfKV1HrdweA9",
             type: "hotel",
             hp_link: "https://www.innthepark.jp/",
             roomtype: "Roomtype: Hang Tent, Dorm Tent, Chartered Building",
             instagram: "https://www.instagram.com/inn_the_park/?hl=ja",
             facebook: "https://www.facebook.com/INNTHEPARK.JP",
             image:File.open("./app/assets/images/PARK.main.png"),
             image2:File.open("./app/assets/images/PARK.lobby.png"),
             image3:File.open("./app/assets/images/PARK.room.png")
             )
             
Lodge.create!(lodge:  "1166バックパッカーズ",
             prefecture: "長野県",
             postal_code: "〒380-0842",
             address: "長野市西町1048",
             phone_number: "TEL 026-217-2816",
             map: "https://g.page/1166backpackers?share",
             type: "hostel",
             hp_link: "https://1166bp.com/",
             roomtype: "Roomtype: Male dormitory, Female dormitory, Japanese Modern",
             instagram: "https://www.instagram.com/1166bp/?hl=ja",
             facebook: "https://www.facebook.com/1166backpackers",
             image:File.open("./app/assets/images/1166.main.jpg"),
             image2:File.open("./app/assets/images/1166.lobby.jpg"),
             image3:File.open("./app/assets/images/1166.room.jpg")
             )
             
Lodge.create!(lodge:  "Name came Ono",
             prefecture: "福井県",
             postal_code: "〒912-0061",
             address: "大野市篠座町7-2",
             phone_number: "TEL 090-5220-5800",
             map: "https://g.page/namakemono?share",
             type: "hostel",
             hp_link: "https://www.namecameono.com/",
             roomtype: "Roomtype: Male dormitory, Female dormitory, Economy Triple, Economy Twin",
             instagram: "https://www.instagram.com/cafe_name_came_ono/?hl=ja",
             facebook: "https://www.facebook.com/namecameono",
             image:File.open("./app/assets/images/ono.main.jpg"),
             image2:File.open("./app/assets/images/ono.lobby.jpg"),
             image3:File.open("./app/assets/images/ono.room.jpg")
             )
             
Lodge.create!(lodge:  "ゲストハウスIRAGO",
             prefecture: "愛知県",
             postal_code: "〒441-3502",
             address: "田原市赤羽根町寺山",
             phone_number: "TEL 090-5220-5800",
             map: "https://goo.gl/maps/tQJke4FAbi7F9pnq9",
             type: "hostel",
             hp_link: "http://www.guesthouse-irago.com/index.html",
             roomtype: "Roomtype: Single room",
             instagram: "https://www.instagram.com/guest_house_irago/?hl=ja",
             facebook: "",
             image:File.open("./app/assets/images/IRAGO.main.jpg"),
             image2:File.open("./app/assets/images/IRAGO.lobby.jpg"),
             image3:File.open("./app/assets/images/IRAGO.room.jpg")
             )
             
Lodge.create!(lodge:  "里山十帖",
             prefecture: "新潟県",
             postal_code: "〒949-6361",
             address: "南魚沼市大沢1209-6",
             phone_number: "TEL 025-783-6777",
             map: "https://goo.gl/maps/JSfi6THeETNdTrWn8",
             type: "hotel",
             hp_link: "http://www.satoyama-jujo.com/",
             roomtype: "Roomtype: Family, Suite Twin",
             instagram: "https://www.instagram.com/satoyamajujo/?hl=ja",
             facebook: "https://www.facebook.com/jiyujin.japan",
             image:File.open("./app/assets/images/里山.main.jpg"),
             image2:File.open("./app/assets/images/里山.lobby.jpg"),
             image3:File.open("./app/assets/images/里山.room.jpg")
             )
             
Lodge.create!(lodge:  "箱根本箱",
             prefecture: "神奈川県",
             postal_code: "〒250-0408",
             address: "足柄下郡箱根町強羅1320-491",
             phone_number: "TEL 0460-83-8025",
             map: "https://goo.gl/maps/WwCwAZiafNBmZWGV7",
             type: "hotel",
             hp_link: "http://hakonehonbako.com/",
             roomtype: "Roomtype: Family, Suite Twin",
             instagram: "https://www.instagram.com/hakonehonbako/?hl=ja",
             facebook: "https://www.facebook.com/hakonehonbako",
             image:File.open("./app/assets/images/本箱.main.jpg"),
             image2:File.open("./app/assets/images/本箱.lobby.jpg"),
             image3:File.open("./app/assets/images/本箱.room.jpg")
             )
             
Lodge.create!(lodge:  "松本本箱",
             prefecture: "長野県",
             postal_code: "〒390-0303",
             address: "松本市浅間温泉3-13-1",
             phone_number: "TEL 025-783-6777",
             map: "https://goo.gl/maps/XMp8mZQdJ225XLMR7",
             type: "hotel",
             hp_link: "https://matsumotojujo.com/",
             roomtype: "Roomtype: Family, Suite Twin",
             instagram: "https://www.instagram.com/matsumoto_jujo/?hl=ja",
             facebook: "https://www.facebook.com/matsumotojujo",
             image:File.open("./app/assets/images/松本.main.jpg"),
             image2:File.open("./app/assets/images/松本.lobby.jpg"),
             image3:File.open("./app/assets/images/松本.room.jpg")
             )
             
Lodge.create!(lodge:  "サンキューヒポポタマスホステル",
             prefecture: "長野県",
             postal_code: "〒390-0875",
             address: "松本市城西2-5-18",
             phone_number: "TEL 070-1560-2223",
             map: "https://goo.gl/maps/pZDo56A1XRScXB6f7",
             type: "hostel",
             hp_link: "https://thankyouhippo.com/",
             roomtype: "Roomtype: Mix dormitory, Family, Triple, Small Twin",
             instagram: "https://www.instagram.com/thankyouhippo/?hl=ja",
             facebook: "https://www.facebook.com/thankyouhippo",
             image:File.open("./app/assets/images/ヒポポ.main.jpg"),
             image2:File.open("./app/assets/images/ヒポポ.lobby.jpg"),
             image3:File.open("./app/assets/images/ヒポポ.room.jpg")
             )

Lodge.create!(lodge:  "tabi-shiro GUESTHOUSE & LOUNGE",
             prefecture: "長野県",
             postal_code: "〒390-0875",
             address: "松本市城西城西1-3-6",
             phone_number: "TEL 0263-88-3453",
             map: "https://goo.gl/maps/618qSBiiRKboiVSH6",
             type: "hostel",
             hp_link: "https://tabi-shiro.com/",
             roomtype: "Roomtype: Mix dormitory, Female dormitory, Japanese Modern",
             instagram: "https://www.instagram.com/tabishiro/?hl=ja",
             facebook: "https://www.facebook.com/tabishiro2016/",
             image:File.open("./app/assets/images/tabi.main.jpg"),
             image2:File.open("./app/assets/images/tabi.lobby.jpg"),
             image3:File.open("./app/assets/images/tabi.room.jpg")
             )
             
Lodge.create!(lodge:  "温泉の宿 ゲストハウス雷鳥",
             prefecture: "長野県",
             postal_code: "〒390-1520",
             address: "松本市安曇4306",
             phone_number: "TEL 0263-93-2746",
             map: "https://goo.gl/maps/i1SUMq7wxMJCBANn7",
             type: "hostel",
             hp_link: "https://ghraicho.com/",
             roomtype: "Roomtype: Japanese Modern Economy, Family, Twin",
             instagram: "https://www.instagram.com/guesthouse_raicho/?hl=ja",
             facebook: "https://www.facebook.com/ghraicho",
             image:File.open("./app/assets/images/雷鳥.main.jpg"),
             image2:File.open("./app/assets/images/雷鳥.lobby.jpg"),
             image3:File.open("./app/assets/images/雷鳥.room.jpg")
             )
             
Lodge.create!(lodge:  "ミンカハウス",
             prefecture: "長野県",
             postal_code: "〒399-0000",
             address: "松本市深志3-1-7",
             phone_number: "TEL ",
             map: "https://goo.gl/maps/UCPdt5BjKxnbL6Us9",
             type: "hostel",
             hp_link: "https://matsumotominkahous.wixsite.com/minkahouse",
             roomtype: "Roomtype: Mix dormitory, Mix Single dormitory, Deluxe Queen, Economy Triple",
             instagram: "https://www.instagram.com/matsumoto.minkahouse/?hl=ja",
             facebook: "https://www.facebook.com/Matsumoto.minkahouse",
             image:File.open("./app/assets/images/ミンカ.main.jpg"),
             image2:File.open("./app/assets/images/ミンカ.lobby.jpg"),
             image3:File.open("./app/assets/images/ミンカ.room.jpg")
             )
             
Lodge.create!(lodge:  "古白",
             prefecture: "奈良県",
             postal_code: "〒630-8335",
             address: "奈良市鳴川町10",
             phone_number: "TEL 0742-81-4236",
             map: "https://goo.gl/maps/k8bJuMpxSvN2Mu5T9",
             type: "hostel",
             hp_link: "http://nara-kohaku.com/",
             roomtype: "Roomtype: Mix dormitory, Female dormitory, Japanese Modern",
             instagram: "https://www.instagram.com/g.kohaku/?hl=ja",
             facebook: "https://www.facebook.com/n.gachikou",
             image:File.open("./app/assets/images/古白.main.jpg"),
             image2:File.open("./app/assets/images/古白.lobby.jpg"),
             image3:File.open("./app/assets/images/古白.room.jpg")
             )
             
Lodge.create!(lodge:  "Guest House縁",
             prefecture: "奈良県",
             postal_code: "〒630-8335",
             address: "奈良市鳴川町10",
             phone_number: "TEL ",
             map: "https://goo.gl/maps/5ybCmkZibFt5iAkA7",
             type: "hostel",
             hp_link: "https://hotel.travel.rakuten.co.jp/hinfo/?f_no=168237",
             roomtype: "Roomtype: Small Double, Small Twin, Triple, Economy room for 4 people",
             instagram: "https://www.instagram.com/enguesthousenara/?hl=ja",
             facebook: "",
             image:File.open("./app/assets/images/EN.main.jpg"),
             image2:File.open("./app/assets/images/EN.lobby.jpg"),
             image3:File.open("./app/assets/images/EN.room.jpg")
             )
             
Lodge.create!(lodge:  "ゲストハウス枕",
             prefecture: "奈良県",
             postal_code: "〒630-8374",
             address: "奈良市今御門町27-1",
             phone_number: "TEL 0742-24-2279",
             map: "https://goo.gl/maps/oSdUVVsXBab3jpvY9",
             type: "hostel",
             hp_link: "http://www.guesthouse-makura.com/",
             roomtype: "Roomtype: Mix Dormitory, Twin",
             instagram: "https://www.instagram.com/guesthouse_makura/?hl=ja",
             facebook: "https://www.facebook.com/guesthousemakura",
             image:File.open("./app/assets/images/枕.main.jpg"),
             image2:File.open("./app/assets/images/枕.lobby.jpg"),
             image3:File.open("./app/assets/images/枕.room.jpg")
             )
             
Lodge.create!(lodge:  "潤 hotobil (女性専用)",
             prefecture: "奈良県",
             postal_code: "〒630-8142",
             address: "奈良市肘塚町181-15",
             phone_number: "TEL 0742-37-3278",
             map: "https://goo.gl/maps/B7T5emoqiYEe5kPp8",
             type: "hostel",
             hp_link: "http://hotobil.com/",
             roomtype: "Roomtype: Japanese Modern, Western Style",
             instagram: "",
             facebook: "https://www.facebook.com/%E5%A5%88%E8%89%AF%E3%81%AE%E5%A5%B3%E6%80%A7%E5%B0%82%E7%94%A8%E3%82%B2%E3%82%B9%E3%83%88%E3%83%8F%E3%82%A6%E3%82%B9-%E6%BD%A4-hotobil-176435375785249",
             image:File.open("./app/assets/images/潤.main.jpg"),
             image2:File.open("./app/assets/images/潤.lobby.jpg"),
             image3:File.open("./app/assets/images/潤.room.jpg")
             )
             
Lodge.create!(lodge:  "奈良ゲストハウス神奈寐",
             prefecture: "奈良県",
             postal_code: "〒630-8306",
             address: "奈良市紀寺町1054",
             phone_number: "TEL 0742-77-2765",
             map: "https://goo.gl/maps/TXtp49GdrEtXcPz58",
             type: "hostel",
             hp_link: "http://www.kamunabi.net/",
             roomtype: "Roomtype: Male dormitory, Female dormitory, Twin, Japanese Modern",
             instagram: "https://www.instagram.com/kamunabi2016/?hl=ja",
             facebook: "https://www.facebook.com/narakamunabi",
             image:File.open("./app/assets/images/神奈寐.main.jpg"),
             image2:File.open("./app/assets/images/神奈寐.lobby.jpg"),
             image3:File.open("./app/assets/images/神奈寐.room.jpg")
             )
             
Lodge.create!(lodge:  "ELEVEN VILLAGE 吹屋",
             prefecture: "岡山県",
             postal_code: "〒719-2341",
             address: "高梁市成羽町吹屋836",
             phone_number: "TEL 050-5435-0665",
             map: "https://g.page/elevenvillage?share",
             type: "hostel",
             hp_link: "https://www.elevenvillage.org/",
             roomtype: "Roomtype: Twin",
             instagram: "https://www.instagram.com/elevenvillage/?hl=ja",
             facebook: "https://www.facebook.com/ELEVENVILLAGE2010",
             image:File.open("./app/assets/images/ELEVEN.main.png"),
             image2:File.open("./app/assets/images/ELEVEN.lobby.png"),
             image3:File.open("./app/assets/images/ELEVEN.room.png")
             )
             
Lodge.create!(lodge:  "とりいくぐる GUESTHOUSE & LOUNGE",
             prefecture: "岡山県",
             postal_code: "〒700-0026",
             address: "岡山市北区奉還町4-7-15",
             phone_number: "TEL 086-250-2629",
             map: "https://goo.gl/maps/1X36Hh9z794xpnf46",
             type: "hostel",
             hp_link: "http://toriikuguru.com/",
             roomtype: "Roomtype: Economy Twin, Japanese Modern",
             instagram: "https://www.instagram.com/toriikuguru/?hl=ja",
             facebook: "https://www.facebook.com/toriikuguru",
             image:File.open("./app/assets/images/とりい.main.jpg"),
             image2:File.open("./app/assets/images/とりい.lobby.jpg"),
             image3:File.open("./app/assets/images/とりい.room.jpg")
             )
             
Lodge.create!(lodge:  "瀬戸内隠れ家リゾートCiera",
             prefecture: "広島県",
             postal_code: "〒722-0061",
             address: "尾道市百島町2586-22",
             phone_number: "TEL 0848-38-2007",
             map: "https://g.page/setouchi-ciela?share",
             type: "hotel",
             hp_link: "https://ciela.jp/",
             roomtype: "Roomtype: Isolated House",
             instagram: "https://www.instagram.com/setouchikakuregaresorts/?hl=ja",
             facebook: "https://www.facebook.com/setouchikakuregaresorts",
             image:File.open("./app/assets/images/ciera.main.png"),
             image2:File.open("./app/assets/images/ciera.lobby.png"),
             image3:File.open("./app/assets/images/ciera.room.png")
             )
             
Lodge.create!(lodge:  "ONOMICHI U2 HOTEL CYCLE",
             prefecture: "広島県",
             postal_code: "〒722-0037",
             address: "尾道市西御所町5-11",
             phone_number: "TEL 0848-21-0550",
             map: "https://goo.gl/maps/qLyupLpBkVBN6KK19",
             type: "hotel",
             hp_link: "https://onomichi-u2.com/",
             roomtype: "Roomtype: Deluxe Twin, Twin",
             instagram: "https://www.instagram.com/onomichi_u2/?hl=ja",
             facebook: "https://www.facebook.com/onomichi.u2",
             image:File.open("./app/assets/images/U2.main.jpg"),
             image2:File.open("./app/assets/images/U2.lobby.jpg"),
             image3:File.open("./app/assets/images/U2.room.jpg")
             )
    
Lodge.create!(lodge:  "あなごのねどこ",
             prefecture: "広島県",
             postal_code: "〒722-0037",
             address: "尾道市西御所町5-11",
             phone_number: "TEL 0848-21-0550",
             map: "https://goo.gl/maps/qLyupLpBkVBN6KK19",
             type: "hostel",
             hp_link: "http://anago.onomichisaisei.com/",
             roomtype: "Roomtype: Mix dormitory, Female dormitory",
             instagram: "",
             facebook: "https://www.facebook.com/Anagononedoko",
             image:File.open("./app/assets/images/あなご.main.jpg"),
             image2:File.open("./app/assets/images/あなご.lobby.jpg"),
             image3:File.open("./app/assets/images/あなご.room.jpg")
             )
             
Lodge.create!(lodge:  "Tami Tottori",
             prefecture: "鳥取県",
             postal_code: "〒689-0712",
             address: "東伯郡湯梨浜町大字中興寺340-1",
             phone_number: "TEL 0858-41-2026",
             map: "https://goo.gl/maps/9bnZSfeG2Q6EaWoF8",
             type: "hostel",
             hp_link: "http://www.tamitottori.com/",
             roomtype: "Roomtype: Male dormitory, Female dormitory, Japanese Modern",
             instagram: "",
             facebook: "",
             image:File.open("./app/assets/images/たみ.main.png"),
             image2:File.open("./app/assets/images/たみ.lobby.jpg"),
             image3:File.open("./app/assets/images/たみ.room.jpg")
             )
             
Lodge.create!(lodge:  "大山バックパッカーズ",
             prefecture: "鳥取県",
             postal_code: "〒689-4101",
             address: "西伯郡伯耆町小林123-39",
             phone_number: "TEL 0858-57-7428",
             map: "https://goo.gl/maps/QC2SBqG1WQYjqkFZ9",
             type: "hostel",
             hp_link: "https://daisen-backpackers.com/",
             roomtype: "Roomtype: Single-use, Twin, Triple, Family",
             instagram: "",
             facebook: "https://www.facebook.com/daisenbp",
             image:File.open("./app/assets/images/大山.main.png"),
             image2:File.open("./app/assets/images/大山.lobby.png"),
             image3:File.open("./app/assets/images/大山.room.png")
             )
             
Lodge.create!(lodge:  "暮らす宿　他郷阿部家",
             prefecture: "島根県",
             postal_code: "〒694-0305",
             address: "大田市大森町 ハ159-1",
             phone_number: "TEL 0854-89-0022",
             map: "https://goo.gl/maps/c1iLMuisJpayh9YN9",
             type: "hotel",
             hp_link: "https://www.gungendo.co.jp/pages/details/000118.php",
             roomtype: "Roomtype: Japanese Modern, Western Style",
             instagram: "https://www.instagram.com/takyo_abeke_jp/?hl=ja",
             facebook: "https://www.facebook.com/TakyoAbeke",
             image:File.open("./app/assets/images/他郷.main.png"),
             image2:File.open("./app/assets/images/他郷.lobby.png"),
             image3:File.open("./app/assets/images/他郷.room.png")
             )
             
Lodge.create!(lodge:  "輝雲荘",
             prefecture: "島根県",
             postal_code: "〒699-2501",
             address: "大田市温泉津町温泉津ロ202-1",
             phone_number: "TEL 0855-65-2008",
             map: "https://goo.gl/maps/yRXtVuVvjMrkGVGw7",
             type: "hotel",
             hp_link: "http://www.kiunsoh.com/",
             roomtype: "Roomtype: Japanese Modern, Family",
             instagram: "https://www.instagram.com/kiunsoh/?hl=ja",
             facebook: "https://www.facebook.com/kiunsoh.yunotsu",
             image:File.open("./app/assets/images/輝雲荘.main.jpg"),
             image2:File.open("./app/assets/images/輝雲荘.lobby.jpg"),
             image3:File.open("./app/assets/images/輝雲荘.room.jpg")
             )
             
Lodge.create!(lodge:  "uzuhouse",
             prefecture: "山口県",
             postal_code: "〒750-0003",
             address: "下関市阿弥陀寺町7-8",
             phone_number: "TEL 083-250-9787",
             map: "https://g.page/uzuhouse?share",
             type: "hostel",
             hp_link: "https://uzuhouse.com/",
             roomtype: "Roomtype: Mix dormitory, Female dormitory, Japanese Modern, Superior, Twin",
             instagram: "https://www.instagram.com/uzuhouse/?hl=ja",
             facebook: "https://www.facebook.com/uzuhouse",
             image:File.open("./app/assets/images/uzu.main.jpg"),
             image2:File.open("./app/assets/images/uzu.lobby.jpg"),
             image3:File.open("./app/assets/images/uzu.room.jpg")
             )
             
Lodge.create!(lodge:  "門司港ゲストハウス PORTO",
             prefecture: "福岡県",
             postal_code: "〒801-0873",
             address: "北九州市門司区東門司1-10-6",
             phone_number: "TEL 093-342-9938",
             map: "https://goo.gl/maps/n4KJyyzRZ2bipPjM6",
             type: "hostel",
             hp_link: "https://moji-porto.com/",
             roomtype: "Roomtype: Single, Double, Twin",
             instagram: "https://www.instagram.com/mojikoguesthouse_porto/?hl=ja",
             facebook: "https://www.facebook.com/MojikoGuestHouse.PORTO",
             image:File.open("./app/assets/images/ポルト.main.jpg"),
             image2:File.open("./app/assets/images/ポルト.lobby.jpg"),
             image3:File.open("./app/assets/images/ポルト.room.jpg")
             )
             
Lodge.create!(lodge:  "小屋場只只",
             prefecture: "山口県",
             postal_code: "〒745-0057",
             address: "周南市大字大津島2763",
             phone_number: "TEL 0834-85-2800",
             map: "https://goo.gl/maps/Np8bKob4s3DEiBBh8",
             type: "hotel",
             hp_link: "http://koyaba.info/",
             roomtype: "Roomtype: Single, Double, Twin",
             instagram: "",
             facebook: "https://www.facebook.com/pages/%E5%B0%8F%E5%B1%8B%E5%A0%B4%20%E5%8F%AA%E5%8F%AA/392704820744781/",
             image:File.open("./app/assets/images/小屋場.main.jpg"),
             image2:File.open("./app/assets/images/小屋場.lobby.png"),
             image3:File.open("./app/assets/images/小屋場.room.png")
             )
             
Lodge.create!(lodge:  "扉温泉 明神館",
             prefecture: "長野県",
             postal_code: "〒390-0222",
             address: "松本市大字入山辺8967",
             phone_number: "TEL 0263-31-2301",
             map: "https://g.page/myojinkan?share",
             type: "ryokan",
             hp_link: "http://www.tobira-group.com/myojinkan/",
             roomtype: "Roomtype: Japanese Modern, Superior King, Deluxe Twin",
             instagram: "https://www.instagram.com/tobiraonsen.myojinkan/?hl=ja",
             facebook: "https://www.facebook.com/tobira.myojinkan",
             image:File.open("./app/assets/images/明神館.main.jpg"),
             image2:File.open("./app/assets/images/明神館.lobby.jpg"),
             image3:File.open("./app/assets/images/明神館.room.jpg")
             )
             
Lodge.create!(lodge:  "海sora アネックス",
             prefecture: "愛媛県",
             postal_code: "〒794-1309",
             address: "今治市大三島町宗方7450",
             phone_number: "TEL 0897-74-1318",
             map: "https://goo.gl/maps/VYEbGJfQZ24VRYMFA",
             type: "ryokan",
             hp_link: "https://hanamusubi.biz/",
             roomtype: "Roomtype: Cottage",
             instagram: "https://www.instagram.com/umisora_hanamusubi/?hl=ja",
             facebook: "https://www.facebook.com/hanamusubi.umisora",
             image:File.open("./app/assets/images/アネックス.main.png"),
             image2:File.open("./app/assets/images/アネックス.lobby.png"),
             image3:File.open("./app/assets/images/アネックス.room.jpg")
             )
             
Lodge.create!(lodge:  "4S STAY Awaikeda Ekimae",
             prefecture: "徳島県",
             postal_code: "〒778-0003",
             address: "三好市池田町サラダ1804-9",
             phone_number: "TEL 0883-70-0166",
             map: "https://goo.gl/maps/QcNk2iBSxnUhCzj16",
             type: "hostel",
             hp_link: "https://4s-stay.com/ekimae/",
             roomtype: "Roomtype: Japanese Modern",
             instagram: "https://www.instagram.com/4s_stay_awaikeda/?hl=ja",
             facebook: "https://www.facebook.com/4SSTAYAwaikeda",
             image:File.open("./app/assets/images/4S.main.jpg"),
             image2:File.open("./app/assets/images/4S.lobby.jpg"),
             image3:File.open("./app/assets/images/4S.room.jpg")
             )
             
Lodge.create!(lodge:  "WAKUWAKUHOUSE MATBA",
             prefecture: "徳島県",
             postal_code: "〒778-0102",
             address: "三好市西祖谷山村今久保175番地",
             phone_number: "TEL 090-2789-7256",
             map: "https://g.page/matba1?share",
             type: "hostel",
             hp_link: "https://waku2house.com/",
             roomtype: "Roomtype: Triple, Family",
             instagram: "https://www.instagram.com/wakuwakuhouse_matba/?hl=ja",
             facebook: "",
             image:File.open("./app/assets/images/waku.main.jpg"),
             image2:File.open("./app/assets/images/waku.lobby.jpg"),
             image3:File.open("./app/assets/images/waku.room.jpg")
             )
            
Lodge.create!(lodge:  "ホテルリソル京都 河原町三条",
             prefecture: "京都府",
             postal_code: "〒604-8031",
             address: "京都市中京区大黒町59-1",
             phone_number: "TEL 075-255-9269",
             map: "https://goo.gl/maps/hm3wSdcbtr19MMtf9",
             type: "hotel",
             hp_link: "https://www.resol-kyoto-k.com/",
             roomtype: "Roomtype: Superior Twin, Twin, Small Double",
             instagram: "https://www.instagram.com/resol_kyoto_kawaramachi_sanjo/?hl=ja",
             facebook: "",
             image:File.open("./app/assets/images/リソル.main.jpg"),
             image2:File.open("./app/assets/images/リソル.lobby.jpg"),
             image3:File.open("./app/assets/images/リソル.room.jpg")
             )
             
Lodge.create!(lodge:  "Hostel and Dining Tanga Table",
             prefecture: "福岡県",
             postal_code: "〒802-0077",
             address: "北九州市小倉北区馬借1-5-25 ホラヤビル 4F",
             phone_number: "TEL 093-967-6284",
             map: "https://g.page/TangaTable?share",
             type: "hostel",
             hp_link: "https://tangatable.jp/",
             roomtype: "Roomtype: Mix dormitory, Female dormitory, Double, Japanese Modern",
             instagram: "https://www.instagram.com/tangatable/?hl=ja",
             facebook: "https://www.facebook.com/TangaTable",
             image:File.open("./app/assets/images/tanga.main.png"),
             image2:File.open("./app/assets/images/tanga.lobby.png"),
             image3:File.open("./app/assets/images/tanga.room.png")
             )
             
Lodge.create!(lodge:  "bbb haus",
             prefecture: "福島県",
             postal_code: "〒819-1323",
             address: "糸島市志摩小金丸1897",
             phone_number: "TEL 092-327-8020",
             map: "https://goo.gl/maps/Ndq4xAokTQRwKvFD7",
             type: "hostel",
             hp_link: "http://www.bbbhaus.com/",
             roomtype: "Roomtype: Twin",
             instagram: "https://www.instagram.com/bbbhaus1897/?hl=ja",
             facebook: "https://www.facebook.com/Bbb-haus-103520291312528",
             image:File.open("./app/assets/images/bbb.main.png"),
             image2:File.open("./app/assets/images/bbb.lobby.jpg"),
             image3:File.open("./app/assets/images/bbb.room.jpg")
             )
             
Lodge.create!(lodge:  "HafH Nagasaki SAI",
             prefecture: "長崎県",
             postal_code: "〒850-0851",
             address: "長崎市古川町5-21",
             phone_number: "TEL 095-818-8181",
             map: "https://g.page/hafh-nagasaki-sai?share",
             type: "hostel",
             hp_link: "https://hafh.com/properties/1",
             roomtype: "Roomtype: Mix dormitory, Room for 4 people, Triple, Double",
             instagram: "https://www.instagram.com/hafh_nagasaki/?hl=ja",
             facebook: "https://www.facebook.com/HafHNagasakiSAI",
             image:File.open("./app/assets/images/Haf.main.jpg"),
             image2:File.open("./app/assets/images/Haf.lobby.jpg"),
             image3:File.open("./app/assets/images/Haf.room.jpg")
             )
             
Lodge.create!(lodge:  "Tagore Harbor Hostel",
             prefecture: "静岡県",
             postal_code: "〒410-3402",
             address: "沼津市戸田321-17",
             phone_number: "TEL 070-3247-3697",
             map: "https://g.page/TagoreHarborHostel?share",
             type: "hostel",
             hp_link: "https://www.tagorehostel.jp/",
             roomtype: "Roomtype: Mix dormitory, Double with sea view, Twin with sea view",
             instagram: "https://www.instagram.com/tagore_hostel/?hl=ja",
             facebook: "https://www.facebook.com/hosteltagore/?eid=ARBSoUKGtlS_Ki-sZDIUlTHuK2uWnieFG2Cf6OWspoXGFSEEKdMdaO6iLrl7LXREdmMDWK3AQDi7e7ym&hc_ref=ARTYiajBHeftMrT1Gk3mMZQUD-oIvwQVwvOahQ7pPMeEsr7a1uP6VnB_ThKLJJkj4a0&ref=nf_target&__xts__[0]=68.ARAgaO2AYoNzf4xjUfOH1z4q2x_bj0-oNVGJdBMkFRhO3PztJCfAXyJHkPa9AtBOnCIRg2O5c-W7uwcY2TSc6ajY88t0R9EOeLYKal0kdwiDs3stKI4nlJhpJ0VijRVrQG6tEXuidB9_XQpjQkxYNQ_fnanrkj_3aCkozobJ7DORO7cvG4XFk6ETFvr_ht21bv22NvhJVUa7iNrAGTp5U-n7iE6QnOb7SMXPyPhNCNPLX0FHtyL8Ls5nlDGwm5DPle5oEOwU_xbrf_3zcGNTIc9_-wS0yjpMUNj63iABRCAyee_RLvld",
             image:File.open("./app/assets/images/tagore.main.jpg"),
             image2:File.open("./app/assets/images/tagore.lobby.jpg"),
             image3:File.open("./app/assets/images/tagore.room.jpg")
             )
             
Lodge.create!(lodge:  "みなとやゲストハウス",
             prefecture: "長崎県",
             postal_code: "〒811-5301",
             address: "壱岐市芦辺町芦辺浦258",
             phone_number: "TEL 0920-40-0190",
             map: "https://goo.gl/maps/z3EQYH8FU8hTruAb6",
             type: "hostel",
             hp_link: "https://www.minatoya-guesthouse.com/",
             roomtype: "Roomtype: Mix dormitory, Japanese Modern, Western",
             instagram: "https://www.instagram.com/minatoya_guesthouse/?hl=ja",
             facebook: "https://www.facebook.com/nagasaki.minatoya.guesthouse",
             image:File.open("./app/assets/images/みなとや.main.png"),
             image2:File.open("./app/assets/images/みなとや.lobby.jpg"),
             image3:File.open("./app/assets/images/みなとや.room.jpg")
             )
             
Lodge.create!(lodge:  "ゲストハウス和茶美",
             prefecture: "長崎県",
             postal_code: "〒811-5463",
             address: "壱岐市芦辺町箱崎中山触2375",
             phone_number: "TEL 080-1786-6170",
             map: "https://goo.gl/maps/yxMg52GAVhV7fp3U7",
             type: "hostel",
             hp_link: "https://www.wasabi-iki.com/",
             roomtype: "Roomtype: Male dormitory, Female dormitory, Twin with sea view",
             instagram: "https://www.instagram.com/guesthousewasabi/?hl=ja",
             facebook: "https://www.facebook.com/guesthousewasabi",
             image:File.open("./app/assets/images/わさび.main.jpg"),
             image2:File.open("./app/assets/images/わさび.lobby.jpg"),
             image3:File.open("./app/assets/images/わさび.room.jpg")
             )
             
Lodge.create!(lodge:  "Guesthouse LAMP Iki",
             prefecture: "長崎県",
             postal_code: "〒811-5501",
             address: "壱岐市勝本町勝本浦253",
             phone_number: "TEL 0920-40-0071",
             map: "https://goo.gl/maps/dCaQqowB4TZaczTp8",
             type: "hostel",
             hp_link: "https://lamp-guesthouse.com/iki/",
             roomtype: "Roomtype: Mix dormitory, Family, Triple, Superior Twin, Twin",
             instagram: "https://www.instagram.com/lamp_iki/?hl=ja",
             facebook: "https://www.facebook.com/guesthouselamp.iki",
             image:File.open("./app/assets/images/LAMP.main.jpg"),
             image2:File.open("./app/assets/images/LAMP.lobby.jpg"),
             image3:File.open("./app/assets/images/LAMP.room.jpg")
             )
             
Lodge.create!(lodge:  "Hotel Karae",
             prefecture: "佐賀県",
             postal_code: "〒847-0045",
             address: "唐津市京町1783 KARAE3F",
             phone_number: "TEL 0955-53-8068",
             map: "https://goo.gl/maps/xBNyKoh37tKceg2CA",
             type: "hotel",
             hp_link: "https://www.hotelkarae.com/",
             roomtype: "Roomtype: Mix dormitory, Female dormitory, Queen, Deluxe Double, Superior Double, Double, Twin",
             instagram: "https://www.instagram.com/hotel_karae_/?hl=ja",
             facebook: "https://www.facebook.com/karae.karatsu",
             image:File.open("./app/assets/images/karae.main.jpg"),
             image2:File.open("./app/assets/images/karae.lobby.jpg"),
             image3:File.open("./app/assets/images/karae.room.jpg")
             )
             
Lodge.create!(lodge:  "Dot Hostel & Bar",
             prefecture: "山梨県",
             postal_code: "〒401-0305",
             address: "南都留郡富士河口湖町大石1509",
             phone_number: "TEL 0555-25-6151",
             map: "https://g.page/dothostelandbar?share",
             type: "hostel",
             hp_link: "https://dot-hostel.com/",
             roomtype: "Roomtype: Mix dormitory, Family, Superior Twin, Twin",
             instagram: "https://www.instagram.com/dothostel_official/?hl=ja",
             facebook: "https://www.facebook.com/dothostelofficial",
             image:File.open("./app/assets/images/dot.main.jpg"),
             image2:File.open("./app/assets/images/dot.lobby.jpg"),
             image3:File.open("./app/assets/images/dot.room.jpg")
             )
             
Lodge.create!(lodge:  "kagelow Mt.Fuji Hostel kawaguchiko",
             prefecture: "山梨県",
             postal_code: "〒401-0301",
             address: "南都留郡富士河口湖町船津3111-1",
             phone_number: "TEL +81555721357",
             map: "https://goo.gl/maps/sX2yHzm2ynJwYuz69",
             type: "hostel",
             hp_link: "https://kagelow.jp/",
             roomtype: "Roomtype: Mix dormitory, Female dormitory, Family, Queen, Japanese Modern",
             instagram: "https://www.instagram.com/kagelow_mt.fuji_hostel/?hl=ja",
             facebook: "https://www.facebook.com/kagelowmt.fujihostelkawaguchiko",
             image:File.open("./app/assets/images/kagelow.main.jpg"),
             image2:File.open("./app/assets/images/kagelow.lobby.jpg"),
             image3:File.open("./app/assets/images/kagelow.room.jpg")
             )
             
Lodge.create!(lodge:  "KéFU stay & lounge",
             prefecture: "京都府",
             postal_code: "〒602-8476",
             address: "京都市上京区桐木町880",
             phone_number: "TEL 075-748-0456",
             map: "https://g.page/kefustay?share",
             type: "hostel",
             hp_link: "https://ke-fu.jp/",
             roomtype: "Roomtype: Single, Family, Deluxe Double, Double, Twin",
             instagram: "https://www.instagram.com/kefu_staylounge/?hl=ja",
             facebook: "https://www.facebook.com/kefustaylounge",
             image:File.open("./app/assets/images/kefu.main.jpg"),
             image2:File.open("./app/assets/images/kefu.lobby.jpg"),
             image3:File.open("./app/assets/images/kefu.room.jpg")
             )
             
Lodge.create!(lodge:  "HOTEL CULTIA 太宰府",
             prefecture: "福岡県",
             postal_code: "〒818-0117",
             address: "太宰府市宰府3-3-33",
             phone_number: "TEL 0120-210-289",
             map: "https://goo.gl/maps/LJQhxt3QibdizyKW9",
             type: "hotel",
             hp_link: "https://www.cultia-dazaifu.com/",
             roomtype: "Roomtype: Exective, Standard Twin",
             instagram: "https://www.instagram.com/hotel_cultia_dazaifu/?hl=ja",
             facebook: "https://www.facebook.com/pages/Hotel%20Cultia%20%E5%A4%AA%E5%AE%B0%E5%BA%9C/108924367180590",
             image:File.open("./app/assets/images/CULTIA.main.jpg"),
             image2:File.open("./app/assets/images/CULTIA.lobby.jpg"),
             image3:File.open("./app/assets/images/CULTIA.room.jpg")
             )
             
Lodge.create!(lodge:  "ume, yamazoe",
             prefecture: "奈良県",
             postal_code: "〒630-2356",
             address: "山辺郡山添村大字片平452",
             phone_number: "TEL 080-6147-0104",
             map: "https://goo.gl/maps/qeiApaRDnC9dU2e6A",
             type: "hotel",
             hp_link: "https://www.ume-yamazoe.com/",
             roomtype: "Roomtype: Queen, Deluxe Double, Double",
             instagram: "https://www.instagram.com/ume.yamazoe/?hl=ja",
             facebook: "https://www.facebook.com/ume.yamazoe",
             image:File.open("./app/assets/images/ume.main.jpg"),
             image2:File.open("./app/assets/images/ume.lobby.jpg"),
             image3:File.open("./app/assets/images/ume.room.jpg")
             )
             
Lodge.create!(lodge:  "SEKAI HOTEL Fuse",
             prefecture: "大阪府",
             postal_code: "〒577-0841",
             address: "東大阪市足代1-19-1",
             phone_number: "TEL 06-6748-0750",
             map: "https://goo.gl/maps/8aVHqXbG7RdNqGEb7",
             type: "hotel",
             hp_link: "https://www.sekaihotel.jp/area/fuse/",
             roomtype: "Roomtype: Family, Superior room for 4 people, Twin, Mix dormitory",
             instagram: "https://www.instagram.com/sekaihotel/?hl=ja",
             facebook: "https://www.facebook.com/SEKAIHOTEL",
             image:File.open("./app/assets/images/fuse.main.jpg"),
             image2:File.open("./app/assets/images/fuse.lobby.jpg"),
             image3:File.open("./app/assets/images/fuse.room.jpg")
             )
             
Lodge.create!(lodge:  "NIPPONIA HOTEL 串本",
             prefecture: "和歌山県",
             postal_code: "〒649-3503",
             address: "東牟婁郡串本町串本996-1",
             phone_number: "TEL 0735-67-7194",
             map: "https://g.page/nipponia-kushimoto?share",
             type: "hotel",
             hp_link: "https://nipponia-kushimoto.jp/company-info/",
             roomtype: "Roomtype: Double",
             instagram: "https://www.instagram.com/nipponia_kushimoto/?hl=ja",
             facebook: "https://www.facebook.com/nipponia.kushimoto",
             image:File.open("./app/assets/images/串本.main.png"),
             image2:File.open("./app/assets/images/串本.lobby.png"),
             image3:File.open("./app/assets/images/串本.room.png")
             )
             
Lodge.create!(lodge:  "NIPPONIA HOTEL 奈良 ならまち",
             prefecture: "奈良県",
             postal_code: "〒630-8345",
             address: "奈良市西城戸町4",
             phone_number: "TEL 0120-210-289",
             map: "https://goo.gl/maps/eSwTKCPNKkNRfELm9",
             type: "hotel",
             hp_link: "https://www.naramachistay.com/",
             roomtype: "Roomtype: Deluxe Twin, Standard Twin",
             instagram: "https://www.instagram.com/nipponia_naramachi/?hl=ja",
             facebook: "",
             image:File.open("./app/assets/images/ならまち.main.jpg"),
             image2:File.open("./app/assets/images/ならまち.lobby.jpg"),
             image3:File.open("./app/assets/images/ならまち.room.jpg")
             )
             
Lodge.create!(lodge:  "NIPPONIA HOTEL 竹原 製塩町",
             prefecture: "広島県",
             postal_code: "〒725-0022",
             address: "竹原市本町1-4-16",
             phone_number: "TEL 0120-210-289",
             map: "https://goo.gl/maps/KDGnRAS89SApGanR8",
             type: "hotel",
             hp_link: "https://www.nipponia-takehara.com/",
             roomtype: "Roomtype: Standard Twin",
             instagram: "https://www.instagram.com/vmg_takehara_saltwork/?hl=ja",
             facebook: "https://www.facebook.com/NIPPONIAHOTELTAKEHARASALTWORKSTOWN",
             image:File.open("./app/assets/images/竹原.main.jpg"),
             image2:File.open("./app/assets/images/竹原.lobby.jpg"),
             image3:File.open("./app/assets/images/竹原.room.jpg")
             )
             
Lodge.create!(lodge:  "佐原商家町ホテル NIPPONIA",
             prefecture: "千葉県",
             postal_code: "〒287-0003",
             address: "香取市イ1720",
             phone_number: "TEL 0120-210-289",
             map: "https://goo.gl/maps/5PkkAiFkztYDa73P7",
             type: "hotel",
             hp_link: "https://www.nipponia-sawara.jp/",
             roomtype: "Roomtype: Family Suite, Deluxe Twin, Economy Twin, Standard Twin, Twin",
             instagram: "https://www.instagram.com/nipponia_sawara/?hl=ja",
             facebook: "https://www.facebook.com/NipponiaSawara",
             image:File.open("./app/assets/images/佐原.main.jpg"),
             image2:File.open("./app/assets/images/佐原.lobby.jpg"),
             image3:File.open("./app/assets/images/佐原.room.jpg")
             )
             
Lodge.create!(lodge:  "篠山城下町ホテル NIPPONIA",
             prefecture: "兵庫県",
             postal_code: "〒669-2342",
             address: "丹波篠山市西町25 ONAE棟",
             phone_number: "TEL 0120-210-289",
             map: "https://goo.gl/maps/J5kCSE5UoH7cqf2R9",
             type: "hotel",
             hp_link: "https://www.sasayamastay.jp/",
             roomtype: "Roomtype: Villa, Family Suite, Deluxe Twin, Economy Twin, Standard Twin, Twin",
             instagram: "https://www.instagram.com/nipponia_sasayama/?hl=ja",
             facebook: "https://www.facebook.com/SasayamaCastleTownHotelNIPPONIA",
             image:File.open("./app/assets/images/篠山.main.jpg"),
             image2:File.open("./app/assets/images/篠山.lobby.jpg"),
             image3:File.open("./app/assets/images/篠山.room.jpg")
             )
             
Lodge.create!(lodge:  "福住宿場町ホテル NIPPONIA",
             prefecture: "兵庫県",
             postal_code: "〒669-2513",
             address: "丹波篠山市福住378",
             phone_number: "TEL 0120-210-289",
             map: "https://goo.gl/maps/uKHKYY14Tymt1F568",
             type: "hotel",
             hp_link: "https://www.nipponia-fukusumi.com/",
             roomtype: "Roomtype: Luxury room for 4 people, Superior Twin, Standard Twin, Twin",
             instagram: "https://www.instagram.com/nipponia_fukusumi/?hl=ja",
             facebook: "https://www.facebook.com/%E7%A6%8F%E4%BD%8F%E5%AE%BF%E5%A0%B4%E7%94%BA%E3%83%9B%E3%83%86%E3%83%ABNipponia-371061306967205",
             image:File.open("./app/assets/images/福住.main.jpg"),
             image2:File.open("./app/assets/images/福住.lobby.jpg"),
             image3:File.open("./app/assets/images/福住.room.jpg")
             )
             
Lodge.create!(lodge:  "竹田城 城下町 ホテルEN",
             prefecture: "兵庫県",
             postal_code: "〒669-5252",
             address: "朝来市和田 山町 竹田字上町西側363",
             phone_number: "TEL 0120-210-289",
             map: "https://goo.gl/maps/KW5ZgRuD1frm84aC9",
             type: "hotel",
             hp_link: "https://www.takedacastle.jp/",
             roomtype: "Roomtype: 2 bed house, Deluxe Twin, Economy Twin, Standard Twin, Twin",
             instagram: "https://www.instagram.com/takedacastle_en/?hl=ja",
             facebook: "https://www.facebook.com/takedacastle",
             image:File.open("./app/assets/images/竹田城.main.jpg"),
             image2:File.open("./app/assets/images/竹田城.lobby.jpg"),
             image3:File.open("./app/assets/images/竹田城.room.jpg")
             )
             
Lodge.create!(lodge:  "沖縄のひとつ宿 tinto＊tinto",
             prefecture: "沖縄県",
             postal_code: "〒905-0402",
             address: "国頭郡今帰仁村字字渡喜仁385-1",
             phone_number: "TEL 0980-56-5998",
             map: "https://g.page/tintotinto?share",
             type: "ryokan",
             hp_link: "https://tintotinto.com/",
             roomtype: "Roomtype: Beds and Tatami style room, Japanese Tatami style room",
             instagram: "https://www.instagram.com/tinto_tinto/?hl=ja",
             facebook: "https://www.facebook.com/tintotinto.okinawa",
             image:File.open("./app/assets/images/tinto.main.png"),
             image2:File.open("./app/assets/images/tinto.lobby.png"),
             image3:File.open("./app/assets/images/tinto.room.jpg")
             )
             
Lodge.create!(lodge:  "CLASKA",
             prefecture: "東京都",
             postal_code: "〒152-000",
             address: "目黒区中央町1-3-18",
             phone_number: "TEL 03-3719-8121",
             map: "https://goo.gl/maps/CZxX2fjvibrZeTY37",
             type: "hotel",
             hp_link: "https://www.claska.com/",
             roomtype: "Roomtype: ",
             instagram: "https://www.instagram.com/claska_tokyo/?hl=ja",
             facebook: "https://www.facebook.com/claska.tokyo",
             image:File.open("./app/assets/images/CLASKA.main.jpg"),
             image2:File.open("./app/assets/images/CLASKA.lobby.jpg"),
             image3:File.open("./app/assets/images/CLASKA.room.jpg")
             )
             
Lodge.create!(lodge:  "とれとれヴィレッジ",
             prefecture: "和歌山県",
             postal_code: "〒649-2201",
             address: "西牟婁郡白浜町堅田2498-1",
             phone_number: "TEL 0739-42-1100",
             map: "https://goo.gl/maps/E264CoiNsXEwSi3K7",
             type: "hotel",
             hp_link: "https://toretore.com/village/",
             roomtype: "Roomtype: Room for 2,4,6 people",
             instagram: "",
             facebook: "https://www.facebook.com/%E3%81%A8%E3%82%8C%E3%81%A8%E3%82%8C%E3%83%B4%E3%82%A3%E3%83%AC%E3%83%83%E3%82%B8-1865317857026252",
             image:File.open("./app/assets/images/とれとれ.main.jpeg"),
             image2:File.open("./app/assets/images/とれとれ.lobby.jpg"),
             image3:File.open("./app/assets/images/とれとれ.room.jpg")
             )
             
Lodge.create!(lodge:  "マリブホテル",
             prefecture: "神奈川県",
             postal_code: "〒249-0007",
             address: "逗子市小坪5-23-16",
             phone_number: "TEL 0467-23-0077",
             map: "https://goo.gl/maps/Zxd3wNJQ58RxxDgx7",
             type: "hotel",
             hp_link: "https://www.riviera.co.jp/malibuhotel/?gclid=CjwKCAjwh472BRAGEiwAvHVfGieP6l-uyv0_bhSekc9j3R7yKVGLBioA_iu1C9is6Q8MbHFfKheeuxoCUb8QAvD_BwE",
             roomtype: "Roomtype: MARINA VIEW SUITE, PRIVATE VILLA, THE MALIBU SUITE",
             instagram: "https://www.instagram.com/malibu_hotel/?hl=ja",
             facebook: "https://www.facebook.com/malibu.hotel.zushimarina",
             image:File.open("./app/assets/images/マリブ.main.jpg"),
             image2:File.open("./app/assets/images/マリブ.lobby.jpg"),
             image3:File.open("./app/assets/images/マリブ.room.jpeg")
             )
             
Lodge.create!(lodge:  "Tipy records inn",
             prefecture: "神奈川県",
             postal_code: "〒250-0011",
             address: "小田原市栄町2-4-13",
             phone_number: "TEL ",
             map: "https://goo.gl/maps/VEEeeUressDbHaw76",
             type: "hostel",
             hp_link: "http://tipyrecordsinn.com/",
             roomtype: "Roomtype: Economy Triple, Economy Twin",
             instagram: "https://www.instagram.com/tipyrecordsinn/?hl=ja",
             facebook: "https://www.facebook.com/tipyrecordsinn",
             image:File.open("./app/assets/images/tipy.main.jpg"),
             image2:File.open("./app/assets/images/tipy.lobby.png"),
             image3:File.open("./app/assets/images/tipy.room.jpg")
             )
             
Lodge.create!(lodge:  "PLUM HOSTEL",
             prefecture: "神奈川県",
             postal_code: "〒250-0011",
             address: "小田原市4 栄町3-4-17 相湘11栄町ビル 2F-B",
             phone_number: "TEL 080-7699-0404",
             map: "https://goo.gl/maps/22TsgS1QHAPGPYDp6",
             type: "hostel",
             hp_link: "http://www.plumhostel.jp/",
             roomtype: "Roomtype: Mix dormitory, Female dormitory",
             instagram: "https://www.instagram.com/plumhostel/?hl=ja",
             facebook: "https://www.facebook.com/plumhostel",
             image:File.open("./app/assets/images/plum.main.jpg"),
             image2:File.open("./app/assets/images/plum.lobby.jpg"),
             image3:File.open("./app/assets/images/plum.room.jpg")
             )
             
Lodge.create!(lodge:  "Good Trip Hostel & Bar",
             prefecture: "神奈川県",
             postal_code: "〒250-0012",
             address: "小田原市本町2-13-5",
             phone_number: "TEL 0465-59-0120",
             map: "https://goo.gl/maps/jzg7ZA74LsjjSokt9",
             type: "hostel",
             hp_link: "http://goodtrip.hippy.jp/",
             roomtype: "Roomtype: Mix dormitory, Female dormitory, Small Twin",
             instagram: "https://www.instagram.com/goodtriphostelbar/?hl=ja",
             facebook: "https://www.facebook.com/goodtriphostelbar",
             image:File.open("./app/assets/images/good.main.jpg"),
             image2:File.open("./app/assets/images/good.lobby.jpg"),
             image3:File.open("./app/assets/images/good.room.jpg")
             )
             
Lodge.create!(lodge:  "ゲストハウスふたつや",
             prefecture: "鹿児島県",
             postal_code: "〒891-0704",
             address: "南九州市頴娃町別府369",
             phone_number: "TEL 070-4127-4306",
             map: "https://goo.gl/maps/QNaCFtwtqUUPMyYT8",
             type: "hostel",
             hp_link: "https://okosoco-japan.com/guesthouse-futatsuya/",
             roomtype: "Roomtype: ",
             instagram: "https://www.instagram.com/futatsuya_gh/?hl=ja",
             facebook: "https://www.facebook.com/futatsuyaEI",
             image:File.open("./app/assets/images/ふたつや.main.jpg"),
             image2:File.open("./app/assets/images/ふたつや.lobby.jpg"),
             image3:File.open("./app/assets/images/ふたつや.room.jpg")
             )
             
